### ISSUE TITLE
Pull additional data for each match

### ISSUE THREAD

**Issue by rblockbush** [amosbastian/understat#16]
Firstly, thanks for the brilliant package!

Would it be possible to pull additional match data (i.e. all the fields found on the 'stats' tab of a match page) from Understat, either as a a new standalone function, or adding the additional data into results that are pulled through from the 'Understat.get_league_results' function?

So we would get all the following data for each match: CHANCES, GOALS, xG, SHOTS, SHOTS ON TARGET, DEEP, PPDA, xPTS

Many thanks.

**Comment by amosbastian** [comment]
Hey @rblockbush, thanks for the kind words. Will have a look in the weekend to see if this is possible!

**Comment by rblockbush** [comment]
Amazing, many thanks for your swift reply @amosbastian

**Comment by amosbastian** [comment]
Soz didn't have time to look at it, so will check it out tomorrow 😓

**Comment by amosbastian** [comment]
@rblockbush unfortunately I think that data is not available using the same technique used for other data provided by the `understat` package, so you would need to scrape it yourself using a different technique 😞

**Comment by rblockbush** [comment]
@amosbastian no problem, thank you very much for looking. I will try scraping myself!
